mutation WalletKeystoreSubmit($input: WalletKeystoreSubmitInput!) {
  walletKeystoreSubmit(input: $input) {
    wallet {
      walletId
      status
      descriptor
      descriptorFingerprint
      pendingParticipants
    }
  }
}
