mutation WalletRegister($input: WalletRegisterInput!) {
  walletRegister(input: $input) {
    wallet {
      walletId
      status
      threshold
      network
      participants
      pendingParticipants
    }
  }
}
