[package]
name = "kota-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "kota-cli"
path = "src/main.rs"

[[bin]]
name = "write_sdl"
path = "src/bin/write_sdl.rs"

[dependencies]
kota-app = { path = "../app" }
kota-server = { path = "../server" }
core-coordination = { path = "../../core/coordination" }
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
sqlx.workspace = true
job.workspace = true
bitcoin.workspace = true
miniscript.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
